services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: unimark-server
    hostname: server
    restart: always
    environment:
      DATABASE_URL: postgres://unimark:unimark@database:5432/unimark
    ports:
      - 3000:3000
    depends_on:
      - database

  database:
    image: postgres:17.2-alpine
    restart: always
    container_name: unimark-database
    environment:
      POSTGRES_DB: unimark
      POSTGRES_USER: unimark
      POSTGRES_PASSWORD: unimark
    ports:
      - 5432:5432
    volumes:
      - ./.postgres:/var/lib/postgresql/data
