version: "3.7"

services:
  client:
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
    container_name: bookmark-client
    hostname: client
    restart: always
    env_file:
      - .env
    volumes:
      - client_data: /var/www/wishubapp.space/html/

  server:
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    container_name: bookmark-server
    hostname: server
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - database

  database:
    image: postgres:16.1-alpine
    restart: always
    container_name: bookmark-database
    env_file:
      - .env
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./.postgres:/var/lib/postgresql/data

volumes:
  client_data:
